addr = "0.0.0.0:9090"
hello_wav = "hello.wav"

# Requires a local gsv_tts server at port 9094: https://github.com/second-state/gsv_tts
[tts]
platform = "StreamGSV"
url = "http://localhost:9094/v1/audio/stream_speech"
speaker = "cooper"

# Use Groq for fast ASR here
[asr]
url = "https://api.groq.com/openai/v1/audio/transcriptions"
api_key = "gsk_ABCD"
model = "whisper-large-v3"
lang = "en"
prompt = "Hello\n你好\n(noise)\n(bgm)\n(silence)\n"
# Requires a local Silero VAD server at port 9093: https://github.com/second-state/silero_vad_server
vad_url = "http://localhost:9093/v1/audio/vad"
# vad_realtime_url = "ws://localhost:9093/v1/audio/realtime_vad"

# Use Groq for fast LLM here
[llm]
llm_chat_url = "https://api.groq.com/openai/v1/chat/completions"
api_key = "gsk_ABCD"
model = "openai/gpt-oss-20b"
history = 10

# Requires an MCP server running at port 8000
[[llm.mcp_server]]
server = "http://localhost:8000/mcp"
type = "http_streamable"

[[llm.sys_prompts]]
role = "system"
content = """
You are a helpful assistant. Please answer user questions as concise as possible while being accurate and truthful. Use short sentences. Try to be humorous and light-hearted. Respond in the same language as the user.

If the user is speaking English, you must respond in English.

如果用户说中文，你必须用中文回答。

Si l'utilisateur parle français, vous devez répondre en français.

"""
